## Data Issues and Cleaning Decisions

The table below summarizes the main data quality issues identified during the preparation process and the decision made for each issue.

| Data Issue                                     | What I Found                                                                                                                                             | Decision                            | Reason                                                                                                                                                                                                                                    |
| ---------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Missing `creator_id` in orders                 | Some order rows were missing `creator_id`. Among the missing creator IDs, many could be linked back to a creator through `video_id` in the videos table. | **Fix + Flag**                      | I created a cleaned creator field by keeping the original `creator_id` when available and backfilling it from the videos table when `video_id` matched. I also flagged whether the creator ID was original, backfilled, or still missing. |
| Remaining missing creator attribution          | After backfilling from videos, some orders still had no reliable creator attribution.                                                                    | **Flag / Leave**                    | I did not force attribution where there was no reliable creator match. These rows were left unassigned and excluded from creator-level ranking where needed.                                                                              |
| Orders at order-line level                     | The orders table contained multiple rows per order because one order could include multiple SKUs.                                                        | **Leave + Adjust Calculation**      | I kept the order-line grain because it preserves product-level sales detail. For order counts, I used `DISTINCTCOUNT(order_id)` instead of counting rows to avoid overstating completed orders.                                           |
| Different order statuses                       | Orders included completed, pending, cancelled, and refunded statuses.                                                                                    | **Flag / Use Differently**          | I used completed orders only for Net GMV because they represent realized sales. Cancelled and refunded orders were not counted toward Net GMV, but they were used to calculate Refund/Cancel Rate as an order quality signal.             |
| Product ID not unique                          | `product_id` was not unique because multiple SKUs could belong to the same product.                                                                      | **Fix**                             | I joined products to orders using `sku_id` instead of `product_id` because `sku_id` is the more reliable product-level key for order-line analysis.                                                                                       |
| Non-video content types                        | Some orders came from content types such as LIVE, SHOP, or LINKSHARE, not only VIDEO.                                                                    | **Flag / Leave**                    | I kept these records because they still represent valid sales, but I flagged content type so video-based metrics would not be misinterpreted. For video efficiency metrics, I only used valid video-linked content where appropriate.     |
| Video metrics repeated after joining to orders | Joining videos to order-line data can repeat views, likes, comments, and video-level metrics across multiple order rows.                                 | **Flag + Adjust Calculation**       | I avoided summing repeated video metrics directly from the wide order table. Video counts and video-level engagement metrics were calculated using distinct videos or from the videos table when needed.                                  |
| Missing or unmatched video IDs                 | Some order rows had video IDs that did not match the videos table, especially for non-video content types.                                               | **Flag / Leave**                    | I did not drop these rows automatically because they could still represent valid sales. I flagged unmatched video records and excluded them only from video-specific efficiency calculations.                                             |
| Commission values                              | Some commission values required validation or adjustment when calculating commission efficiency.                                                         | **Fix + Flag**                      | I used actual commission paid when available. When commission needed to be estimated using creator commission rate, I flagged the value as estimated so the cost efficiency metric could be interpreted carefully.                        |
| Metrics with different units                   | Net GMV, Net GMV per Video, Completed Orders, Refund/Cancel Rate, and Revenue per Commission Dollar use different units.                                 | **Fix through Normalization**       | I converted each raw KPI into a 0–100 percentile-based score before combining them into the Investment Priority Score. This made the metrics comparable.                                                                                  |
| Refund/Cancel Rate direction                   | Most metrics are better when higher, but Refund/Cancel Rate is better when lower.                                                                        | **Fix through Reverse Scoring**     | I used reverse percentile scoring for Order Quality Score so lower refund/cancel rates receive higher scores.                                                                                                                             |
| Small-sample creators                          | Some creators had very limited order or video activity, which could make their efficiency look artificially high.                                        | **Flag / Filter**                   | I used creator eligibility rules and a Reliability Score based on completed orders to reduce the risk of overvaluing creators with very small samples.                                                                                    |
| Outliers and skewed creator performance        | Creator performance was highly uneven, with a small number of creators driving much larger GMV than others.                                              | **Leave + Normalize**               | I did not remove high-performing outliers because they may represent real business value. Instead, I used percentile-based scoring to reduce the impact of extreme raw values.                                                            |
| Raw follower count                             | Follower count was available but does not directly measure sales conversion.                                                                             | **Leave / Not Core Ranking Metric** | I kept follower count as descriptive context, but I did not use it as a main ranking metric because the business question focuses on sales performance and investment return.                                                             |
